### PR TITLE
tests: features: add obufds test

### PR DESCRIPTION
**Pull request by acomodi**
Signed-off-by: Alessandro Comodi <acomodi@antmicro.com>

This PR adds a basic test for the OBUFDS. Longer term this test might be expanded to include all diff IO tests (e.g. OBUFTDS, IBUFDS, IOBUFDS, etc.).

There is an issue at the moment that concerns the DCP generation from the physical netlist provided by nextpnr. Here is a tar containing the relevant outputs: [obufds tar](https://github.com/SymbiFlow/fpga-interchange-tests/files/6715546/obufds.tar.gz).

The problem seems to be that there is no macro expansion (probably due to a lack of data from the device database) happening for the OBUFDS cell. In fact, the nextpnr-generated physical netlist, there is only one OUTBUF used, and the DIFF_OUT wire is used.
Instead, when building with Vivado, the OBUFDS cell seem to be expanded to include the two OUTBUF bels, alongside with the inverter for the negative output. 

I believe that the correct solution would be to provide the right data to correctly expand the OBUFDS in two OBUFT and an INV cell

### CODE REVIEW

**Comment by gatecat** [comment]
The problem is that there are two possible OBUFDS expansions: one for true differential standards like LVDS (which is the one being picked here) and one for fake differential standards like SSTL here (which requires the two OBFUTs and INV as you've seen).

We will need to pick the right expansion based on the IO standard, see the discussion about this in https://github.com/SymbiFlow/fpga-interchange-schema/pull/40

**Comment by acomodi** [comment]
@gatecat All right, thanks for the info.

I have added some debug lines and noticed that the expansion rules may not be complete, in fact there is only a rule for the OBUFTDS:

```
Info: createContext time 1.90s
Info: Primitive OBUFTDS - Macro name OBUFTDS_DUAL_BUF

Info: Annotating ports with timing budgets for target frequency 12.00 MHz
Info: Checksum: 0xff5cf696

```

I have checked also upon the chipdb generation and indeed, the only rule present is the OBUFTDS one. I wonder whether there might be a bug when filling the `exceptionMap` list from RapidWright.

**Comment by mkurc-ant** [comment]
I've extended the CMake scripts with support for XDC name prefix - this allows to have multiple tests with different XDCs in the same folder.

I also added tests for the rest of differential IO buffers:
| Buffer | Status | GH Issue |
|--------|--------|----------|
| OBUFTDS | ok | N/A |
| OBUFDS | fail | TBD |
| IBUFDS | fail | TBD |
| IOBUFDS | fail | TBD |

**Review by gatecat — COMMENTED** [review]
LGTM once we get CI passing

**Pull request merged**
