### PR TITLE
kokoro: fix artifacts regexp

### PR DESCRIPTION
**Pull request by acomodi**
Signed-off-by: Alessandro Comodi <acomodi@antmicro.com>

### CODE REVIEW

**Review by mithro — APPROVED** [review]
LGTM.

**Comment by acomodi** [comment]
Uploaded artifacts are now only related to tests. Merging.

**Comment by mithro** [comment]
[fpga-interchange-tests/artifacts/prod/foss-fpga-tools/fpga-interchange-tests/presubmit/2/20210429-110953/build](https://console.cloud.google.com/storage/browser/fpga-interchange-tests/artifacts/prod/foss-fpga-tools/fpga-interchange-tests/presubmit/2/20210429-110953/build)

**Comment by mithro** [comment]
There was a permission issue which I fixed.

**Pull request merged**
