### PR TITLE
Design status reports

### PR DESCRIPTION
**Pull request by mkurc-ant**
This PR adds reporting of CI runs for individual test designs making it possible to track which ones pass and which does not.

The design tests are now allowed to fail which does not make the CI go red. Instead build statuses of all relevant CMake targets are collected, processed and embedded in a webpage which is automatically pushed to the `gh-pages` branch of this repository. The webpage gets updated only upon a merge to the `master` branch but is built for every run and is available as an artifact. With GitHub pages set up this page can be used to view and track the progress of designs supported in the FPGA interchange flow.

To maintain the purpose of CI device resource building happens now before running the tests and makes the CI go red in case of a failure.

### CODE REVIEW

**Comment by mkurc-ant** [comment]
The CI should upload the generated status webpage when run from the master branch (hopefully). To do this this PR has to be merged first.

**Review by acomodi — APPROVED** [review]
LGTM.

A question would be how to keep track of regressions at this point, for instance, AFAIU now new tests are allowed to fail, but tests that were previously succeeding cannot be allowed to fail.

**Comment by mkurc-ant** [comment]
Hmmm, actually there is no history tracking now. In the current state before merge one has to manually download artifacts and check if the designs built successfully.

This is not an ideal solution. If you have a method of tracking & checking against historical runs in mind then please suggest it.

**Comment by acomodi** [comment]
We might add a parameter for the tests to allow disabling hard-failures if the test can fail, and add a new target that checks the final report, and call the target at the end of CI, and, in case a test that shouldn't have failed, fails, CI will go red.

But I think that for now we can merge this one, as a report is generated either way and we can still keep track of regressions

**Pull request merged**
