### PR TITLE
Add FD cell to remap_xc7

### PR DESCRIPTION
**Pull request by mtdudek**
Signed-off-by: Maciej Dudek <mdudek@antmicro.com>

### CODE REVIEW

**Comment by gatecat** [comment]
For this to work you also need to read in the remap file as a library of blackboxes before synthesis: https://github.com/gatecat/litex-fpga-interchange/blob/13f5f723e74eb051a444d8740ee7232ccc536ec8/run_yosys.tcl#L5

Otherwise, it will fail as FD isn't currently in Yosys' tech libraries.

**Comment by mtdudek** [comment]
Could You pleas tell me why it needs to be read as blackboxes?
I've just tested it and it passed when used with techmap -map.
Also here https://github.com/SymbiFlow/symbiflow-arch-defs/blob/4df1b0271956e36ff41caa1c97ac209e8525c0a7/xc/xc7/yosys/synth.tcl#L29 it is used just with techmap

**Comment by gatecat** [comment]
This is specifically for FD, which unlike some of the other cells is not in the Yosys blackbox library so will cause an unknown cell type error at hierarchical elaboration time.

Reading in the map file as blackboxes (with -lib) fixes this.

**Comment by mtdudek** [comment]
So you would suggest to move this from this file to let's say lib_xc7.v?

**Comment by gatecat** [comment]
Yeah that seems like one way to do it

**Comment by gatecat** [comment]
This PR now moves it to a separate file, but doesn't actually use it anywhere (it will need to be used both as a blackbox library and as a techmap post-synthesis).

**Pull request closed without merging**
